title: "Max Tassano"
email: max.tassano@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site is a digital resume and project portfolio for Max Tassano. 
# Root directory for your portfolio. On GitHub Pages, this is the name of your repository.
baseurl: "/portfolio-template"
# Protocol + hostname for your portfolio. On GitHub Pages, this is https://yourusername.github.io
url: "https://mlh-fellowship.github.io" 
twitter_username: MaxTassano
github_username: maxtassano
form_url: "https://formspree.io/f/xrgodpqo"
social_image: "./assets/img/social-link.jpg"
social_image_alt: # Alt text for the link preview image
google_analytics_measurement_id: # G-XXXXXXXXXX

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
